# Generated by Django 4.2.9 on 2024-02-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sudayun", "0002_rename_serverfilename_resource_filename_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resource_detail",
            old_name="serverFileName",
            new_name="fileName",
        ),
        migrations.AlterField(
            model_name="resource_detail",
            name="serverTime",
            field=models.DateTimeField(blank=True, null=True, verbose_name="文件时间"),
        ),
    ]
