# Generated by Django 4.2.9 on 2024-02-06 15:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sudayun", "0003_rename_serverfilename_resource_detail_filename_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resource_detail",
            old_name="serverTime",
            new_name="fileTime",
        ),
    ]
