#/etc/dnscrypt-proxy/dnscrypt-proxy.toml

server_names = ['adguard-dns','dnscrypt.eu-dk','dnscrypt.me','DOH-blahdns','quad9-ip4-filter-pri','scaleway-fr', 'google', 'yandex', 'cloudflare']
#listen_addresses = ['0.0.0.0:5353', '[::1]:5353']
listen_addresses = ['0.0.0.0:53530']
max_clients = 250
ipv4_servers = true
ipv6_servers = false
dnscrypt_servers = true
doh_servers = true
require_dnssec = true
require_nolog = true
require_nofilter = true
force_tcp = false
timeout = 2500
keepalive = 30
log_file = '/var/log/dnscrypt-proxy/dnscrypt-proxy.log'
cert_refresh_delay = 240
# Load-balancing options
lb_strategy = 'ph'
#fallback_resolver = '9.9.9.9:53'
# 清华dns
fallback_resolver = '101.6.6.6:53'
ignore_system_dns = false
netprobe_timeout = 30
block_ipv6 = false
cache = true
cache_size = 512
cache_min_ttl = 600
cache_max_ttl = 86400
cache_neg_min_ttl = 60
cache_neg_max_ttl = 600
[query_log]
  # log_file = '/var/log/dnscrypt-proxy/query.log'
  format = 'tsv'
[nx_log]
  file = '/var/log/dnscrypt-proxy/nx.log'
  format = 'tsv'
[blacklist]
  # log_file = '/var/log/dnscrypt-proxy/blocked.log'
[ip_blacklist]
  # log_file = '/var/log/dnscrypt-proxy/ip-blocked.log'
[whitelist]
  # log_file = '/var/log/dnscrypt-proxy/whitelisted.log'
[sources]
  [sources.'public-resolvers']
  urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v2/public-resolvers.md', 'https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md']
  cache_file = '/var/cache/dnscrypt-proxy/public-resolvers.md'
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  refresh_delay = 72
  prefix = ''
